// Data extracted from prototipe KopiPetani.
// `ph` = placeholder styling (emoji + gradient) used when no product image is set.
export const products = [
  // ============ A. SARANA & KEBUTUHAN TANI ============

  // --- Bibit & Benih Kopi (4) ---
  {
    id: 1,
    name: "Bibit Kopi Arabika Gayo Super",
    cat: "Bibit & Benih",
    origin: "Nursery Mitra Tani, Gayo",
    price: 8000,
    old: 10000,
    unit: "/batang",
    image: "https://images.pexels.com/photos/36040372/pexels-photo-36040372.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🌱", c: "linear-gradient(135deg,#5f8f4e,#37622c)" },
    group: "Sarana Tani",
  },
  {
    id: 2,
    name: "Bibit Kopi Robusta Unggul",
    cat: "Bibit & Benih",
    origin: "Nursery Tani Jaya, Lampung",
    price: 7000,
    old: 9000,
    unit: "/batang",
    image: "https://images.pexels.com/photos/29319112/pexels-photo-29319112.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🌱", c: "linear-gradient(135deg,#5f8f4e,#37622c)" },
    group: "Sarana Tani",
  },
  {
    id: 3,
    name: "Benih Kopi Liberika Pilihan",
    cat: "Bibit & Benih",
    origin: "Koperasi Benih Nusantara",
    price: 25000,
    old: 32000,
    unit: "/pack",
    image: "https://images.pexels.com/photos/7125673/pexels-photo-7125673.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🌰", c: "linear-gradient(135deg,#8a6b3f,#5c4626)" },
    group: "Sarana Tani",
  },
  {
    id: 4,
    name: "Bibit Kopi Arabika Siap Tanam",
    cat: "Bibit & Benih",
    origin: "Nursery Mitra Tani, Gayo",
    price: 9000,
    old: 12000,
    unit: "/batang",
    image: "https://images.pexels.com/photos/36040373/pexels-photo-36040373.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🌱", c: "linear-gradient(135deg,#5f8f4e,#37622c)" },
    group: "Sarana Tani",
  },

  // --- Pupuk (organik & non-organik) (4) ---
  {
    id: 5,
    name: "Pupuk Kompos Organik 5kg",
    cat: "Pupuk",
    origin: "Mitra Kompos Lokal",
    price: 30000,
    old: 38000,
    unit: "/karung",
    image: "https://images.pexels.com/photos/25974981/pexels-photo-25974981.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🍂", c: "linear-gradient(135deg,#8a6b3f,#5c4626)" },
    group: "Sarana Tani",
  },
  {
    id: 6,
    name: "Pupuk Kandang Fermentasi 10kg",
    cat: "Pupuk",
    origin: "Tani Organik Sejahtera",
    price: 25000,
    old: 32000,
    unit: "/karung",
    image: "https://images.pexels.com/photos/15671402/pexels-photo-15671402.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🌿", c: "linear-gradient(135deg,#6b5330,#40311b)" },
    group: "Sarana Tani",
  },
  {
    id: 7,
    name: "Pupuk NPK Mutiara 16-16-16",
    cat: "Pupuk",
    origin: "Distributor Tani Makmur",
    price: 90000,
    old: 105000,
    unit: "/5kg",
    image: "https://images.pexels.com/photos/31673795/pexels-photo-31673795.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🧪", c: "linear-gradient(135deg,#3f6d8a,#264660)" },
    group: "Sarana Tani",
  },
  {
    id: 8,
    name: "Pupuk Urea Non-Organik 5kg",
    cat: "Pupuk",
    origin: "Distributor Tani Makmur",
    price: 70000,
    old: 80000,
    unit: "/5kg",
    image: "https://images.pexels.com/photos/31673795/pexels-photo-31673795.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🧴", c: "linear-gradient(135deg,#8a7a3f,#5c4f26)" },
    group: "Sarana Tani",
  },

  // --- Pestisida & Perlindungan Tanaman (3) ---
  {
    id: 9,
    name: "Pestisida Nabati Organik 500ml",
    cat: "Pestisida",
    origin: "Vendor: BioGuard",
    price: 45000,
    old: 55000,
    unit: "/botol",
    image: "https://images.pexels.com/photos/13882449/pexels-photo-13882449.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🌿", c: "linear-gradient(135deg,#4f7d55,#2f5236)" },
    group: "Sarana Tani",
  },
  {
    id: 10,
    name: "Fungisida Anti Karat Daun 250ml",
    cat: "Pestisida",
    origin: "Vendor: AgroCare",
    price: 60000,
    old: 72000,
    unit: "/botol",
    image: "https://images.pexels.com/photos/30912665/pexels-photo-30912665.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🛡️", c: "linear-gradient(135deg,#5a7d4f,#35522f)" },
    group: "Sarana Tani",
  },
  {
    id: 11,
    name: "Sprayer Punggung Manual 16L",
    cat: "Pestisida",
    origin: "Vendor: AgroTools",
    price: 185000,
    old: 220000,
    unit: "/unit",
    image: "https://images.pexels.com/photos/36027197/pexels-photo-36027197.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "💦", c: "linear-gradient(135deg,#3f6d8a,#264660)" },
    group: "Sarana Tani",
  },

  // ============ B. HASIL & PRODUK KOPI ============

  // --- Ceri Kopi Segar (2) ---
  {
    id: 12,
    name: "Ceri Kopi Merah Arabika",
    cat: "Ceri Kopi",
    origin: "Kebun Tani Makmur, Gayo",
    price: 12000,
    old: 15000,
    unit: "/kg",
    image: "https://images.pexels.com/photos/29639314/pexels-photo-29639314.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🍒", c: "linear-gradient(135deg,#7a1f1f,#4a1010)" },
    group: "Hasil Kopi",
  },
  {
    id: 13,
    name: "Ceri Kopi Robusta Pilihan",
    cat: "Ceri Kopi",
    origin: "Kebun Rakyat, Lampung",
    price: 10000,
    old: 13000,
    unit: "/kg",
    image: "https://images.pexels.com/photos/31915996/pexels-photo-31915996.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🍒", c: "linear-gradient(135deg,#7a1f1f,#4a1010)" },
    group: "Hasil Kopi",
  },

  // --- Green Bean / Biji Mentah (2) ---
  {
    id: 14,
    name: "Green Bean Arabika Gayo",
    cat: "Green Bean",
    origin: "Koperasi Tani Gayo",
    price: 85000,
    old: 95000,
    unit: "/kg",
    image: "https://images.pexels.com/photos/37540264/pexels-photo-37540264.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🫘", c: "linear-gradient(135deg,#6a5a3a,#3d3320)" },
    group: "Hasil Kopi",
  },
  {
    id: 15,
    name: "Green Bean Robusta Grade 1",
    cat: "Green Bean",
    origin: "Koperasi Tani Lampung",
    price: 60000,
    old: 70000,
    unit: "/kg",
    image: "https://images.pexels.com/photos/4820773/pexels-photo-4820773.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🫘", c: "linear-gradient(135deg,#6a5a3a,#3d3320)" },
    group: "Hasil Kopi",
  },

  // --- Roasted Bean / Biji Sangrai (2) ---
  {
    id: 16,
    name: "Roasted Bean Arabika Medium Roast",
    cat: "Roasted Bean",
    origin: "Roastery KopiPetani",
    price: 110000,
    old: 125000,
    unit: "/kg",
    image: "https://images.pexels.com/photos/30444143/pexels-photo-30444143.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🔥", c: "linear-gradient(135deg,#5a3620,#3d2311)" },
    group: "Hasil Kopi",
  },
  {
    id: 17,
    name: "Roasted Bean Robusta Dark Roast",
    cat: "Roasted Bean",
    origin: "Roastery KopiPetani",
    price: 85000,
    old: 98000,
    unit: "/kg",
    image: "https://images.pexels.com/photos/30444150/pexels-photo-30444150.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "🔥", c: "linear-gradient(135deg,#4A2210,#2A0E05)" },
    group: "Hasil Kopi",
  },

  // --- Kopi Bubuk (4) ---
  {
    id: 18,
    name: "Kopi Bubuk Arabika Gayo",
    cat: "Kopi Bubuk",
    origin: "Roastery KopiPetani",
    price: 55000,
    old: 65000,
    unit: "/200g",
    image: "https://images.pexels.com/photos/5908468/pexels-photo-5908468.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "☕", c: "linear-gradient(135deg,#4A2210,#2A0E05)" },
    group: "Hasil Kopi",
  },
  {
    id: 19,
    name: "Kopi Bubuk Robusta Asli",
    cat: "Kopi Bubuk",
    origin: "Roastery KopiPetani",
    price: 40000,
    old: 48000,
    unit: "/200g",
    image: "https://images.pexels.com/photos/3847475/pexels-photo-3847475.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "☕", c: "linear-gradient(135deg,#5a3620,#3d2311)" },
    group: "Hasil Kopi",
  },
  {
    id: 20,
    name: "Kopi Bubuk House Blend Premium",
    cat: "Kopi Bubuk",
    origin: "Roastery KopiPetani",
    price: 60000,
    old: 72000,
    unit: "/200g",
    image: "https://images.pexels.com/photos/28495599/pexels-photo-28495599.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "✨", c: "linear-gradient(135deg,#8f5f34,#5c3d20)" },
    group: "Hasil Kopi",
  },
  {
    id: 21,
    name: "Kopi Bubuk Luwak Premium",
    cat: "Kopi Bubuk",
    origin: "Roastery KopiPetani",
    price: 150000,
    old: 180000,
    unit: "/100g",
    image: "https://images.pexels.com/photos/28495604/pexels-photo-28495604.jpeg?auto=compress&cs=tinysrgb&w=600",
    ph: { em: "👑", c: "linear-gradient(135deg,#7a5a20,#4a3610)" },
    group: "Hasil Kopi",
  },
];

export const categories = [
  { k: "Semua", em: "🛍️" },
  { k: "Bibit & Benih", em: "🌱" },
  { k: "Pupuk", em: "🌿" },
  { k: "Pestisida", em: "🛡️" },
  { k: "Ceri Kopi", em: "🍒" },
  { k: "Green Bean", em: "🫘" },
  { k: "Roasted Bean", em: "🔥" },
  { k: "Kopi Bubuk", em: "☕" },
];

export const categorySections = [
  {
    title: "Green Bean",
    items: ["Gayo", "Mandailing", "Toraja", "Kintamani", "Flores", "Java Preanger"],
  },
  {
    title: "Roasted Bean",
    items: ["Light Roast", "Medium Roast", "Dark Roast"],
  },
  {
    title: "Ground Coffee",
    items: ["Espresso", "V60", "French Press", "Tubruk"],
  },
  {
    title: "Paket Kopi",
    description: "Coffee Explorer Box",
    items: ["Gayo", "Toraja", "Flores"],
  },
];

export const featuredFarmers = [
  {
    name: "Amir Syah",
    location: "Gayo, Aceh",
    bio: "Mengelola kebun kopi arabika single origin dengan teknik agroforestry dan pengepakan langsung.",
    tags: ["Arabika", "Sustainability", "Direct Trade"],
    em: "🌿",
  },
  {
    name: "Dewi Lestari",
    location: "Kintamani, Bali",
    bio: "Petani kopi spesialti dengan perhatian detail pada pemetikan ceritera buah terbaik.",
    tags: ["Single Origin", "Small Batch", "Premium"],
    em: "🌺",
  },
  {
    name: "Rudi Pratama",
    location: "Toraja, Sulawesi",
    bio: "Ahli roasting keluarga yang menghadirkan karakter kopi tanah tinggi dengan keseimbangan rasa yang tajam.",
    tags: ["Roasting", "High Altitude", "Authentic"],
    em: "☕",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Aisyah Ananda",
    role: "Barista & Coffee Enthusiast",
    initials: "AA",
    quote: "Kopi terbaik yang pernah saya coba, kualitasnya konsisten dan pelayanan marketplace ini sangat profesional.",
  },
  {
    id: 2,
    name: "Rizal Aditya",
    role: "Pemilik Kedai Kopi",
    initials: "RA",
    quote: "Sistem pemesanan mudah dan produk selalu tiba segar. Saya merasa lebih dekat dengan petani kopi.",
  },
  {
    id: 3,
    name: "Nina Kusuma",
    role: "Pecinta Kopi Rumahan",
    initials: "NK",
    quote: "Pilihan kopinya lengkap, dari green bean hingga kopi sangrai. Sangat cocok untuk eksperimen seduh di rumah.",
  },
];

export function rp(n) {
  return "Rp" + Math.round(n).toLocaleString("id-ID");
}